/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_panic_hook: () => void;
export const __wbg_chunkresult_free: (a: number, b: number) => void;
export const __wbg_get_chunkresult_offset: (a: number) => bigint;
export const __wbg_set_chunkresult_offset: (a: number, b: bigint) => void;
export const __wbg_get_chunkresult_length: (a: number) => number;
export const __wbg_set_chunkresult_length: (a: number, b: number) => void;
export const chunkresult_fingerprint: (a: number) => number;
export const chunkresult_content_hash: (a: number) => number;
export const __wbg_chunker_free: (a: number, b: number) => void;
export const chunker_new: (a: number, b: number, c: number, d: number, e: number) => number;
export const chunker_intoAsyncIterator: (a: number) => number;
export const __wbg_chunksiterator_free: (a: number, b: number) => void;
export const chunksiterator_js_new: () => number;
export const chunksiterator_async_iterator: (a: number) => any;
export const chunksiterator_next: (a: number) => any;
export const __wbg_myasynciterator_free: (a: number, b: number) => void;
export const myasynciterator_new: (a: number, b: number) => number;
export const myasynciterator_next: (a: number) => any;
export const myasynciterator_asyncIterator: (a: number) => any;
export const __wbg_sha256_free: (a: number, b: number) => void;
export const sha256_new: (a: number, b: number) => number;
export const sha256_intoOkId: (a: number) => number;
export const okid_displaySafe: (a: number) => [number, number];
export const okid_fromDisplaySafe: (a: number, b: number) => number;
export const __wbg_uuid_free: (a: number, b: number) => void;
export const uuid_new: () => number;
export const uuid_intoOkId: (a: number) => number;
export const uuid_fromString: (a: number, b: number) => number;
export const uuid_inner: (a: number) => [number, number];
export const __wbg_okid_free: (a: number, b: number) => void;
export const okid_fromString: (a: number, b: number) => [number, number, number];
export const okid_toString: (a: number) => [number, number];
export const okid_hashType: (a: number) => [number, number];
export const okid_toPathSafe: (a: number) => [number, number];
export const okid_fromSha256: (a: number, b: number) => number;
export const okid_fromBlake3: (a: number, b: number) => number;
export const okid_newUuid: () => number;
export const okid_newUlid: () => number;
export const okid_fingerprint: (a: number, b: number) => number;
export const __wbg_blake3_free: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure40_externref_shim: (a: number, b: number, c: any) => void;
export const closure87_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
