/*
 Generated by typeshare 1.13.2
*/

/** Digest of the binary identifier */
export type Digest = string;

export enum BinaryType {
	Unknown = "unknown",
	Sha1 = "sha1",
	Sha256 = "sha256",
	Sha3_512 = "sha3512",
	Blake3 = "blake3",
	Ulid = "ulid",
	Uuid = "uuid",
	Fingerprint = "fingerprint",
}

/** OkId is a double clickable representation of arbitrary binary data */
export interface OkId {
	hash_type: BinaryType;
	digest: Digest;
}

