/*
 Generated by typeshare 1.13.2
 */

import Foundation

/// Digest of the binary identifier
public typealias Digest = String

public enum BinaryType: String, Codable {
	case unknown
	case sha1
	case sha256
	case sha3512
	case blake3
	case ulid
	case uuid
	case fingerprint
}

/// OkId is a double clickable representation of arbitrary binary data
public struct OkId: Codable {
	public let hash_type: BinaryType
	public let digest: Digest

	public init(hash_type: BinaryType, digest: Digest) {
		self.hash_type = hash_type
		self.digest = digest
	}
}
