// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BinaryType = "Unknown" | "Sha1" | "Sha256" | "Sha3_512" | "Blake3" | "Ulid" | "Uuid" | "Fingerprint";
