// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryType } from "./BinaryType";
import type { Digest } from "./Digest";

/**
 * The digest of the binary identifier
 */
export type OkId = { hash_type: BinaryType, 
/**
 * The digest of the binary identifier
 */
digest: Digest, };
