name: Cat File Workflow

on:
  # Trigger the workflow on push or pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allow manually triggering the workflow
  workflow_dispatch:
    inputs:
      file-path:
        description: 'Path of the file to cat'
        required: true
        default: 'README.md'
        type: string

jobs:
  cat-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Display file content from workflow dispatch input
        if: github.event_name == 'workflow_dispatch'
        run: |
          FILE_PATH="${{ github.event.inputs.file-path }}"
          echo "Displaying content of file: $FILE_PATH"
          echo "----------------------------------------"
          if [ -f "$FILE_PATH" ]; then
            cat "$FILE_PATH"
          else
            echo "Error: File '$FILE_PATH' not found!"
            exit 1
          fi
      
      - name: Display default file (README.md) for push/PR events
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "Displaying content of README.md:"
          echo "----------------------------------------"
          if [ -f "README.md" ]; then
            cat README.md
          else
            echo "No README.md file found in repository"
            # List files in root directory
            echo "Files in repository root:"
            ls -la
          fi
